# Site settings
title: svelte-kit-launcher
description: A CLI tool to quickly scaffold SvelteKit projects with your preferred setup

remote_theme: pages-themes/time-machine@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme