# Site settings
title: svelte-pi
description: Quickly scaffold SvelteKit projects

remote_theme: pages-themes/dinky@v0.2.0
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme