# gh pages config
theme: jekyll-theme-hacker
title: SvelteKit Launcher
description: A CLI tool to quickly scaffold SvelteKit projects with your preferred setup

# github pages config
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme